GMAIL_USER: 'galleryofficial@gmail.com'
GMAIL_SECRET: 'qwertyazsxdc'
GOOGLE_MAP: 'AIzaSyBs8K7eayFPLgyZzC-KZCLDgLz_N09-gTc'
#GOOGLE_YOUTUBE: 'AIzaSyBs8K7eayFPLgyZzC-KZCLDgLz_N09-gTc'

development:
  FB_KEY: '1997533793805209'
  FB_SECRET: 'ed28000574a370346a5e6545444a0ae9'
#  VK_KEY: '5057616 '
#  VK_SECRET: 'QMSZSLIfHdnO2AYcgZDw'

production:
  FB_KEY: '1742037066025482'
  FB_SECRET: '4dc95722b83370784f7eb902b38d7a44'
  #  VK_KEY: '5048141'
#  VK_SECRET: '3k4ZUhzY6Q6JcqV755Kg'